---
# Source: spring-music/templates/service.yaml
kind: Service     
apiVersion: v1     
metadata:
  name: my-app #from RELEASE NAME
spec:
  selector:
    app: my-app    
  type: ClusterIP  #from values
  ports:         
  - name: http   
    protocol: TCP
    port: 80 #from Values
    targetPort: 8000  #from values
---
# Source: spring-music/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector: 
    matchLabels:
      app: my-app
  replicas: 2   #from values
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app #from values
        image: lilo977/my-app:0.26 #from values
        ports:
        - containerPort: 8000
